baseURL = "https://yazilim.aykutasil.com/"

theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "yazilimaykutasil"
paginate        = 20
#SectionPagesMenu = "main"
canonifyurls    = false

[params]
  title       = "My Book"
  subtitle    = "Software"
  copyright   = "© 2018"

  cover       = "img/istanbul_marti.jpg"
  description = "Aykut Asil Software Notes"
  metaDescription = "aykuttasil"
  googleAnalytics = "UA-42457939-6"
  customCSS = []
  RSSLink = ""

  twitterName = "aykuttasil"
  fbName = "aykuttasil"
  githubName = "aykuttasil"
  linkedinName = "aykuttasil"
  mediumName = "aykuttasil"

  logo = "img/aykutasil.jpg"
  orgName = "AA"
  orgWebsite = "https://aykutasil.com"
  orgDescription = ""

  showSupport = true

  author = "Aykut Asil"
  authorAvatar = "img/aykutasil.jpg"
  authorLocation = "Istanbul, Turkey"
  authorWebsite = "https://aykutasil.com"
  authorDescription = "Software Developer"

  pageNotFoundTitle = "Sayfa Bulunamadı!"

  #casper or caspertwo
  singleViewStyle = "casper"


  keywords = ["aykutasil", "aykuttasil","develop","software","yazilim",
  "android","java","javascript","c#","csharp","nodejs","kotlin","dart","flutter",
  "mobile","mobile-developer","software-craftsmanship"]
  

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Android"
  url = "/tags/android/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99


